services:
  - type: web
    name: ewaste-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ewaste-db
          property: connectionString
      - key: FLASK_APP
        value: app.py
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true 